### ISSUE TITLE
WT32-eth01 

### ISSUE THREAD

**Issue by Eponas07** [esphome/bluetooth-proxies#18]
have ordered the WT32-eth01 and wanted to flash this pber the website unfortunately I can no longer select this is no longer supported ? Thank you

**Comment by balloob** [comment]
See #16. The YAML is still at https://github.com/esphome/bluetooth-proxies/blob/main/wt32-eth01.yaml and it will be added back in the future

**Comment by nagyrobi** [comment]
WT32-eth01 works perfectly as a proxy, it's just that you have to flash it manually atm, not via the website.

**Comment by Eponas07** [comment]
Thanks for your answers Am unfortunately just starting, how can I flash the manually sorry Von meinem iPhone gesendetAm 14.09.2022 um 20:22 schrieb H. Árkosi Róbert ***@***.***>:﻿
WT32-eth01 works perfectly as a proxy, it's just that you have to flash it manually atm, not via the website.

**Comment by nagyrobi** [comment]
Follow this thread: https://community.home-assistant.io/t/how-i-installed-esphome-on-the-wt32-eth01/359027

**Comment by balloob** [comment]
The installer is now also available again on the website https://esphome.github.io/bluetooth-proxies/?diy

**Comment by Eponas07** [comment]
Thx 👍Von meinem iPhone gesendetAm 18.09.2022 um 18:52 schrieb Paulus Schoutsen ***@***.***>:﻿
The installer is now also available again on the website https://esphome.github.io/bluetooth-proxies/?diy
