### ISSUE TITLE
lan eth doesn't work

### ISSUE THREAD

**Issue by 645340633** [esphome/bluetooth-proxies#19]
Hello guys，the GL-S10 I bought last week firmware is v2.1。I flash the esphome firmware but then the lan eth connect to the switch or router, there is no effect,   the router eth light doesn't flicker. please help what should I do.
![IMG_20220917_035130_edit_13714920821864](https://user-images.githubusercontent.com/80463778/190834926-ea63a9bb-fff2-4ef6-95a4-189efa8139ac.jpg)
![IMG_20220917_035137_edit_13771805250501](https://user-images.githubusercontent.com/80463778/190834929-8219fcf0-ac0c-402f-b53f-5eb8cd374eaa.jpg)

**Comment by 645340633** [comment]
it looks like this

**Comment by nagyrobi** [comment]
@blakadder

**Comment by blakadder** [comment]
That's a v2.1 board apparently designed in may this year which cannot be same as mine since I got mine in February 2022. nothing now with Chinese manufacturers, different innards, model number still the same
 ![](https://blakadder.com/assets/images/gl-s10/pcb.jpg)

**Comment by pvizeli** [comment]
My was an v2.3

**Comment by blakadder** [comment]
geez, fast development cycle there, can you take a nice image so i can document it
