### ISSUE TITLE
Homekit Support?

### ISSUE THREAD

**Issue by abishur** [esphome/bluetooth-proxies#26]
I'm trying get an understanding of the capabilities of the bluetooth proxy, will this allow me to forward homekit bluetooth devices or is that something that's completely infeasible?

**Comment by nagyrobi** [comment]
Please ask direct support questions in our Discord channel.

**Comment by abishur** [comment]
Oh, sorry, is that the ESPhome one or is there one specifically for bluetooth proxies?

**Comment by balloob** [comment]
The goal is to allow HA to talk to HomeKit devices via bluetooth proxies. It does not work yet.
