### ISSUE TITLE
Error when adopting from esphome

### ISSUE THREAD

**Issue by patatman** [esphome/bluetooth-proxies#32]
I just installed the bluetooth proxy using: https://esphome.github.io/bluetooth-proxies/
But after trying to adopt the board in my local esphome, I got an error:
`[active] is an invalid option for [bluetooth proxy]`

Removed the active part on the generic-esp yaml.

https://github.com/esphome/bluetooth-proxies/pull/31 should fix it.

**Comment by Nardol** [comment]
`active` is not on the stable version but on dev.
If you use the latest ESPHome dev version, you will be able to use `active` with `bluetooth_proxy`

**Comment by patatman** [comment]
Aha! Thanks for clarifying, I'll remove my PR.
