### ISSUE TITLE
Problems with ESP32 NodeMCU & GL-S10

### ISSUE THREAD

**Issue by Lampyridae1984** [esphome/bluetooth-proxies#35]
I flashed an ESP32 NodeMCU through the online Proxy web tool (I choose generic ESP32) and initially everything seems to work ok. But not long after the ESP32 turns unavailable in HA. Has anyone else had this issue?

I also bought two GL-S10 units, but they too seem to just stop working and loop. When I first tried to flash them, I realized that the configuration through the portal (i.e. the yaml config on Github) was set for the wrong (newer) hardware revision of the units, so I flashed them manually with the correct ethernet settings (I have a V1.0 and V1.3). But as I said, eventually they will stop working and the network led flashes frantically. Am I missing something?

Are there some steps I might have missed?

**Comment by tomi19921702** [comment]
Got the same problem, trying to find a solution.

**Comment by Lampyridae1984** [comment]
I kinda got the ESP32 NodeMCU to work for a short moment, using it together with my Mi Flora sensors. 

It managed to retrieve the data from most but not all sensors (i.e. temperature, humidity, moisture, light, conductivity & battery). But eventually, one by one, they turned unavailable. When I restart the ESP32 it kinda finds some of them, but eventually everything turns unavailable again.

I can speed this down spiraling process up significantly by simply simply reloading the Xiaomi BLE/Flower care integration. After that they seemingly no longer update for at least several hours. No sure tho if the problem is the ESP32 with BT proxy or something in HA OS/core. 🤷🏻‍♂️

**Comment by nagyrobi** [comment]
How far are your ESP32 nodes from network equipment? (Routers, Switches, Laptops, PCs)

I get stable results by taking this in consideration: https://community.home-assistant.io/t/increase-polling-with-xiaomi-temperature-sensors/357522/8
(the article was originally written when the sensors were implemented by `pvvx_mithermometer` platform, but switched since to `bluetooth_proxy`, all observations apply the same way)

**Comment by Lampyridae1984** [comment]
> How far are your ESP32 nodes from network equipment? (Routers, Switches, Laptops, PCs)

Both close to my router and across my 95 sqm apartment. Same result. Before BT proxy was released I used the same ESP32 to track the Mi Flora sensors with the ESPHome Mi flora (HHCCJCY01) sensor "integration" without any problems (except for the battery sensors).

**Comment by Lampyridae1984** [comment]
> I get stable results by taking this in consideration: https://community.home-assistant.io/t/increase-polling-with-xiaomi-temperature-sensors/357522/8
> (the article was originally written when the sensors were implemented by `pvvx_mithermometer` platform, but switched since to `bluetooth_proxy`, all observations apply the same way)

The post looks interesting, I'll look at it during the weekend. Cheers!

**Comment by balloob** [comment]
Please limit issues to 1 topic. You've added two and now this issue is not actionable.

**Comment by Lampyridae1984** [comment]
> Please limit issues to 1 topic.

Oops, sorry. Didn't think that one through.
