### ISSUE TITLE
switchbot curtain works only 1 cover

### ISSUE THREAD

**Issue by italoc** [esphome/bluetooth-proxies#38]
i have an esp32 with esp bluetooth-proxies and 2 switchbot curtain, and i don't know why, but works only 1 curtain at time, with the switchbot app all works great.

i receive this error

bleak_retry_connector.BleakConnectionError:  (F5:FA:27:95:XX:XX) - F5:FA:27:95:XX:XX: Failed to connect: No backend with an available connection slot that can reach address F5:FA:27:95:XX:XX was found

**Comment by balloob** [comment]
Bluetooth proxies are currently limited to 1 active connection at a time. It will support 3 in a future update. The error you're seeing means that the active connection is being used for one of your curtains, and so it's not available for another curtain.
