### ISSUE TITLE
Xiaomi Mijia Motion Sensor 2 (RTCGQ02LM)

### ISSUE THREAD

**Issue by Anzic23** [esphome/bluetooth-proxies#45]
Transmits only "end of motion detection". During integration requested a 32-character code, received it via token extractor, the sensor was added, but only Signal Strength and Light objects (with Light transmitting the value "off", after a couple of minutes, after moving in front of the sensor). how can I help in providing additional information? HA 2022.10.3

**Comment by jesserockz** [comment]
This is not the place for this kind of issue, although I do not really understand the problem you are having. Please create an issue in the home assistant core repo issue tracker.
