### ISSUE TITLE
Web installer not asking for wifi credentials

### ISSUE THREAD

**Issue by joostbijl** [esphome/bluetooth-proxies#51]
Hi, 

i'm trying to flash a 'regular' esp32 with esphome to act as a bt proxy to ha via https://esphome.github.io/bluetooth-proxies/. 

I'm using a esp32-wroom32 dev board.

It connects fine to the browser and i can succesfully install the 'generic esp3' firmware. When i click next after the 'success' message, i don't get prompted for the wifi credentials but instead go back to the previous screen.

Am i doing something wrong? Or is the web installer broken?

Joost

**Comment by joostbijl** [comment]
The question i posted was specific to the web installer. Funny thing is that the 3rd time i did it, it asked me for the wifi credentials.

**Comment by balloob** [comment]
I wonder if we need to wait longer for the ESP to respond to finding Improv. I've seen it a few times (but not 2/3 times) that the ESP didn't respond in time that it supported Wi-Fi provisioning.
