### ISSUE TITLE
The AP mode is not work to config network

### ISSUE THREAD

**Issue by gl-chenxiaosheng** [esphome/bluetooth-proxies#56]
I use the firmwre by this web [esp32Generic](https://esphome.github.io/bluetooth-proxies/?diy). But it doesn't work in AP mode, I check the [esp32-generic.yaml](https://github.com/esphome/bluetooth-proxies/blob/main/esp32-generic.yaml) find it commented out the captive_portal.

**Comment by nagyrobi** [comment]
It's commented out because it's not yet compatible with `esp-idf`. This is being worked on.

**Comment by nagyrobi** [comment]
Also: https://github.com/esphome/bluetooth-proxies/issues/46#issue-1409528311
