### ISSUE TITLE
Question: BLE + HTTPS coexistence 

### ISSUE THREAD

**Issue by jshep321** [esphome/bluetooth-proxies#63]
I spent some months writing custom firmware for ESP32-WROOM (4MB) a couple of years ago.  One of the challenges was to have BLE stack coexist with https due to size limitations.  I had to change to a smaller BLE stack (nimble) to get things to work.  Has anyone encountered/explored these problems or are they a thing of the past?  Before I start deploying on my multiple ESP32's I'd love to know if I'm going to have to reflash over UART due to this issue?

Thanks!

**Comment by balloob** [comment]
ESPHome does not use HTTPS. It uses Noise encryption with it's socket-based native API and supports OTA with bluetooth proxies.
