### ISSUE TITLE
Wifi connection only with visible SSID

### ISSUE THREAD

**Issue by clfberlin** [esphome/bluetooth-proxies#89]
I use separate SSIDs (and VLANs) for iot and entertainment devices. My ESP32 Bluetooth modules (CP2102) will unfortunately only connect to their WiFi when the SSID is visible.

**Comment by gregcsw** [comment]
You need to add fast_connect: true into the wifi config.

wifi:
   ssid: !secret wifi_ssid_iot
   password: !secret wifi_password_iot
   fast_connect: true
  # Enable fast_connect for hidden wifi networks'

**Comment by clfberlin** [comment]
Thank you, @gregcsw 
fast_connect: true does indeed do the job.
I appreciate your help!
