### ISSUE TITLE
Instalattion fails on M5Stack Atom Lite (Failed to download manifest)

### ISSUE THREAD

**Issue by Darkangeel-hd** [esphome/bluetooth-proxies#96]
I tried using the web a few keeps ago and it worked like a charm, may have something to do with the recent changes in the project.

The error the webinstaller gives after selection of the serial port is "_Failed to download manifest_"
![image](https://github.com/user-attachments/assets/ea3ecae4-0549-4479-9172-c70af4bf8bf3)

Behind the scenes, is trying to request this file `https://firmware.esphome.io/bluetooth-proxy/m5stack-atom-lite/manifest.json`
but it ends up in a 404.

If I try to use the generic ESP32, it then request 
`https://firmware.esphome.io/bluetooth-proxy/esp32-generic/manifest.json` which completes successfully with a 200 status and the installation can proceed.

Is there anything I can do to help / diagnose / fix this issue?

**Comment by hamsando** [comment]
Same issue with the bluetooth-proxy for olimex esp32 poe iso. I raised https://github.com/esphome/firmware/issues/255.

**Comment by jesserockz** [comment]
Fixed by #97 and releasing now. Sorry. I thought I had tested this, but clearly I didnt.

**Comment by jesserockz** [comment]
This is now fixed on the website

**Comment by Darkangeel-hd** [comment]
> Fixed by #97 and releasing now. Sorry. I thought I had tested this, but clearly I didnt.

I can confirm it's fixed and working again, thanks!
Mistakes happens, don't beat you to it
